# Generated by Django 5.0.6 on 2024-06-19 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('monthly_allocation', models.IntegerField(null=True)),
                ('allocation_due', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('issued_to', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=255)),
                ('amount_issued', models.PositiveIntegerField()),
                ('amount_owing', models.CharField(max_length=50)),
                ('coupon_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.record')),
            ],
        ),
    ]
