# Generated by Django 5.0.6 on 2024-06-19 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_recepient_issuedmonthly'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedmonthly',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='issuedmonthly',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.recepient'),
        ),
    ]
