# Generated by Django 5.0.6 on 2024-06-19 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_issuedmonthly_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedmonthly',
            name='issued_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='coupons.recepient'),
        ),
    ]
