# Generated by Django 5.0.6 on 2024-06-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_alter_issuedmonthly_issued_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedmonthly',
            name='designation',
        ),
    ]
