# Generated by Django 5.0.6 on 2024-06-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_remove_issuedmonthly_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('issued_to', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=255)),
                ('number_of_coupons', models.PositiveIntegerField(null=True)),
                ('amount_issued', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
