# Generated by Django 5.0.6 on 2024-06-19 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_serviceissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceissue',
            name='coupon_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coupons.record'),
        ),
    ]
